// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AuthFoundation.Models;
using Microsoft.EntityFrameworkCore;

namespace AuthFoundation.Data;

public partial class OsolabAuthContext : DbContext
{
    public OsolabAuthContext(DbContextOptions<OsolabAuthContext> options)
        : base(options)
    {
    }

    public virtual DbSet<client_data_key> client_data_keys { get; set; }

    public virtual DbSet<client_master> client_masters { get; set; }

    public virtual DbSet<data_key_master> data_key_masters { get; set; }

    public virtual DbSet<osolab_user> osolab_users { get; set; }

    public virtual DbSet<user_info> user_infos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<client_data_key>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("client_data_key", "auth");

            entity.Property(e => e.client_id)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.data_key)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.client_data_keys)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_data_key_client_id");

            entity.HasOne(d => d.data_keyNavigation).WithMany(p => p.client_data_keys)
                .HasForeignKey(d => d.data_key)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_data_key_data_key");
        });

        modelBuilder.Entity<client_master>(entity =>
        {
            entity.HasKey(e => e.client_id);

            entity.ToTable("client_master", "auth");

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.client_name)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.client_secret)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<data_key_master>(entity =>
        {
            entity.HasKey(e => e.data_key);

            entity.ToTable("data_key_master", "auth");

            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<osolab_user>(entity =>
        {
            entity.HasKey(e => e.osolab_id);

            entity.ToTable("osolab_user", "auth");

            entity.HasIndex(e => e.email, "IX_osolab_user_email");

            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nonce)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<user_info>(entity =>
        {
            entity.HasKey(e => new { e.osolab_id, e.client_id, e.data_key });

            entity.ToTable("user_info", "auth");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.data_key, e.status }, "IX_user_info_osolab_id_client_id_data_key_status");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.status }, "IX_user_info_osolab_id_client_id_status");

            entity.HasIndex(e => new { e.osolab_id, e.status }, "IX_user_info_osolab_id_status");

            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.data_value)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.user_infos)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_info_client_id");

            entity.HasOne(d => d.osolab).WithMany(p => p.user_infos)
                .HasForeignKey(d => d.osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_info_osolab_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}