// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using AuthFoundation.Models;
using Microsoft.EntityFrameworkCore;

namespace AuthFoundation.Data;

public partial class OsolabAuthContext : DbContext
{
    public OsolabAuthContext(DbContextOptions<OsolabAuthContext> options)
        : base(options)
    {
    }

    public virtual DbSet<agent_audit_log> agent_audit_logs { get; set; }

    public virtual DbSet<agent_delegation> agent_delegations { get; set; }

    public virtual DbSet<agent_master> agent_masters { get; set; }

    public virtual DbSet<client_data_key> client_data_keys { get; set; }

    public virtual DbSet<client_master> client_masters { get; set; }

    public virtual DbSet<client_redirect_uri> client_redirect_uris { get; set; }

    public virtual DbSet<client_scope> client_scopes { get; set; }

    public virtual DbSet<client_term> client_terms { get; set; }

    public virtual DbSet<data_key_master> data_key_masters { get; set; }

    public virtual DbSet<jwk_master> jwk_masters { get; set; }

    public virtual DbSet<osolab_user> osolab_users { get; set; }

    public virtual DbSet<scope_data_key> scope_data_keys { get; set; }

    public virtual DbSet<scope_master> scope_masters { get; set; }

    public virtual DbSet<user_client_scope_consent> user_client_scope_consents { get; set; }

    public virtual DbSet<user_info> user_infos { get; set; }

    public virtual DbSet<user_term_consent> user_term_consents { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<agent_audit_log>(entity =>
        {
            entity.HasKey(e => e.audit_log_id);

            entity.ToTable("agent_audit_log", "auth");

            entity.HasIndex(e => new { e.agent_id, e.create_datetime }, "IX_agent_audit_log_agent_id_create_datetime");

            entity.HasIndex(e => new { e.owner_osolab_id, e.create_datetime }, "IX_agent_audit_log_owner_osolab_id_create_datetime");

            entity.Property(e => e.agent_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.delegation_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.event_type)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.ip_address).HasMaxLength(64);
            entity.Property(e => e.owner_osolab_id).HasMaxLength(16);
            entity.Property(e => e.resource).HasMaxLength(255);
            entity.Property(e => e.result)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.scope)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.user_agent).HasMaxLength(512);

            entity.HasOne(d => d.agent).WithMany(p => p.agent_audit_logs)
                .HasForeignKey(d => d.agent_id)
                .HasConstraintName("FK_agent_audit_log_agent_id");

            entity.HasOne(d => d.delegation).WithMany(p => p.agent_audit_logs)
                .HasForeignKey(d => d.delegation_id)
                .HasConstraintName("FK_agent_audit_log_delegation_id");

            entity.HasOne(d => d.owner_osolab).WithMany(p => p.agent_audit_logs)
                .HasForeignKey(d => d.owner_osolab_id)
                .HasConstraintName("FK_agent_audit_log_owner_osolab_id");
        });

        modelBuilder.Entity<agent_delegation>(entity =>
        {
            entity.HasKey(e => e.delegation_id);

            entity.ToTable("agent_delegation", "auth");

            entity.HasIndex(e => new { e.agent_id, e.client_id, e.status }, "IX_agent_delegation_agent_id_client_id_status");

            entity.HasIndex(e => new { e.owner_osolab_id, e.status }, "IX_agent_delegation_owner_osolab_id_status");

            entity.Property(e => e.delegation_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.agent_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.expires_datetime).HasPrecision(0);
            entity.Property(e => e.owner_osolab_id).HasMaxLength(16);
            entity.Property(e => e.revoked_datetime).HasPrecision(0);
            entity.Property(e => e.scopes)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);
            entity.Property(e => e.verified_datetime).HasPrecision(0);

            entity.HasOne(d => d.agent).WithMany(p => p.agent_delegations)
                .HasForeignKey(d => d.agent_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_agent_delegation_agent_id");

            entity.HasOne(d => d.client).WithMany(p => p.agent_delegations)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_agent_delegation_client_id");

            entity.HasOne(d => d.owner_osolab).WithMany(p => p.agent_delegations)
                .HasForeignKey(d => d.owner_osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_agent_delegation_owner_osolab_id");
        });

        modelBuilder.Entity<agent_master>(entity =>
        {
            entity.HasKey(e => e.agent_id);

            entity.ToTable("agent_master", "auth");

            entity.HasIndex(e => new { e.owner_osolab_id, e.status }, "IX_agent_master_owner_osolab_id_status");

            entity.Property(e => e.agent_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.agent_name).HasMaxLength(128);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.last_used_datetime).HasPrecision(0);
            entity.Property(e => e.owner_osolab_id).HasMaxLength(16);
            entity.Property(e => e.revoked_datetime).HasPrecision(0);
            entity.Property(e => e.secret_hash)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.owner_osolab).WithMany(p => p.agent_masters)
                .HasForeignKey(d => d.owner_osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_agent_master_owner_osolab_id");
        });

        modelBuilder.Entity<client_data_key>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("client_data_key", "auth");

            entity.HasIndex(e => new { e.client_id, e.data_key }, "UQ_client_data_key_client_id_data_key").IsUnique();

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.client_data_keys)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_data_key_client_id");

            entity.HasOne(d => d.data_keyNavigation).WithMany(p => p.client_data_keys)
                .HasForeignKey(d => d.data_key)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_data_key_data_key");
        });

        modelBuilder.Entity<client_master>(entity =>
        {
            entity.HasKey(e => e.client_id);

            entity.ToTable("client_master", "auth");

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.client_name).HasMaxLength(64);
            entity.Property(e => e.client_secret)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<client_redirect_uri>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("client_redirect_uri", "auth");

            entity.HasIndex(e => new { e.client_id, e.redirect_uri, e.status }, "IX_client_redirect_uri_client_id_redirect_uri_status");

            entity.HasIndex(e => new { e.client_id, e.status }, "IX_client_redirect_uri_client_id_status");

            entity.HasIndex(e => new { e.client_id, e.redirect_uri }, "UQ_client_redirect_uri_client_id_redirect_uri").IsUnique();

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.redirect_uri).HasMaxLength(2048);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.client_redirect_uris)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_redirect_uri_client_id");
        });

        modelBuilder.Entity<client_scope>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("client_scope", "auth");

            entity.HasIndex(e => new { e.client_id, e.scope }, "UQ_client_scope_client_id_scope").IsUnique();

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.required).HasDefaultValue((byte)1, "DF_client_scope_required");
            entity.Property(e => e.scope)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.client_scopes)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_scope_client_id");

            entity.HasOne(d => d.scopeNavigation).WithMany(p => p.client_scopes)
                .HasForeignKey(d => d.scope)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_scope_scope");
        });

        modelBuilder.Entity<client_term>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("client_term", "auth");

            entity.HasIndex(e => new { e.client_id, e.term_id }, "UQ_client_term_client_id_term_id").IsUnique();

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.required).HasDefaultValue((byte)1, "DF_client_term_required");
            entity.Property(e => e.term_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.term_url).HasMaxLength(2048);
            entity.Property(e => e.term_version)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.client_terms)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_client_term_client_id");
        });

        modelBuilder.Entity<data_key_master>(entity =>
        {
            entity.HasKey(e => e.data_key);

            entity.ToTable("data_key_master", "auth");

            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<jwk_master>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("jwk_master", "auth");

            entity.HasIndex(e => new { e.status, e.update_datetime }, "IX_jwk_master_status_update_datetime");

            entity.HasIndex(e => e.kid, "UQ_jwk_master_kid").IsUnique();

            entity.Property(e => e.alg)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.key_use)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.kid)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.kty)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.private_key_iv).HasMaxLength(12);
            entity.Property(e => e.private_key_tag).HasMaxLength(16);
            entity.Property(e => e.public_e)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.public_n)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<osolab_user>(entity =>
        {
            entity.HasKey(e => e.osolab_id);

            entity.ToTable("osolab_user", "auth");

            entity.HasIndex(e => e.email, "IX_osolab_user_email");

            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nonce)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.password)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<scope_data_key>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("scope_data_key", "auth");

            entity.HasIndex(e => new { e.scope, e.data_key }, "UQ_scope_data_key_scope_data_key").IsUnique();

            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.scope)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.data_keyNavigation).WithMany(p => p.scope_data_keys)
                .HasForeignKey(d => d.data_key)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_scope_data_key_data_key");

            entity.HasOne(d => d.scopeNavigation).WithMany(p => p.scope_data_keys)
                .HasForeignKey(d => d.scope)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_scope_data_key_scope");
        });

        modelBuilder.Entity<scope_master>(entity =>
        {
            entity.HasKey(e => e.scope);

            entity.ToTable("scope_master", "auth");

            entity.Property(e => e.scope)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.description).HasMaxLength(255);
            entity.Property(e => e.update_datetime).HasPrecision(0);
        });

        modelBuilder.Entity<user_client_scope_consent>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("user_client_scope_consent", "auth");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.scope }, "UQ_user_client_scope_consent_osolab_id_client_id_scope").IsUnique();

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.consented_datetime).HasPrecision(0);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.scope)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.user_client_scope_consents)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_client_scope_consent_client_id");

            entity.HasOne(d => d.osolab).WithMany(p => p.user_client_scope_consents)
                .HasForeignKey(d => d.osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_client_scope_consent_osolab_id");

            entity.HasOne(d => d.scopeNavigation).WithMany(p => p.user_client_scope_consents)
                .HasForeignKey(d => d.scope)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_client_scope_consent_scope");
        });

        modelBuilder.Entity<user_info>(entity =>
        {
            entity.HasKey(e => new { e.osolab_id, e.client_id, e.data_key });

            entity.ToTable("user_info", "auth");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.data_key, e.status }, "IX_user_info_osolab_id_client_id_data_key_status");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.status }, "IX_user_info_osolab_id_client_id_status");

            entity.HasIndex(e => new { e.osolab_id, e.status }, "IX_user_info_osolab_id_status");

            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.data_key)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.data_value).HasMaxLength(4000);
            entity.Property(e => e.update_datetime).HasPrecision(0);

            entity.HasOne(d => d.client).WithMany(p => p.user_infos)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_info_client_id");

            entity.HasOne(d => d.osolab).WithMany(p => p.user_infos)
                .HasForeignKey(d => d.osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_info_osolab_id");
        });

        modelBuilder.Entity<user_term_consent>(entity =>
        {
            entity.HasKey(e => e.sequence_id);

            entity.ToTable("user_term_consent", "auth");

            entity.HasIndex(e => new { e.osolab_id, e.client_id, e.term_id, e.consented_datetime }, "IX_user_term_consent_osolab_id_client_id_term_id_consented_datetime");

            entity.Property(e => e.client_id)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.consented_datetime).HasPrecision(0);
            entity.Property(e => e.create_datetime).HasPrecision(0);
            entity.Property(e => e.osolab_id).HasMaxLength(16);
            entity.Property(e => e.term_id)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.term_version)
                .HasMaxLength(32)
                .IsUnicode(false);

            entity.HasOne(d => d.client).WithMany(p => p.user_term_consents)
                .HasForeignKey(d => d.client_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_term_consent_client_id");

            entity.HasOne(d => d.osolab).WithMany(p => p.user_term_consents)
                .HasForeignKey(d => d.osolab_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_term_consent_osolab_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
