// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;

namespace AuthFoundation.Models;

public partial class agent_audit_log
{
    public long audit_log_id { get; set; }

    public string? agent_id { get; set; }

    public string? owner_osolab_id { get; set; }

    public string? delegation_id { get; set; }

    public string event_type { get; set; } = null!;

    public string? client_id { get; set; }

    public string? scope { get; set; }

    public string? resource { get; set; }

    public string result { get; set; } = null!;

    public string? ip_address { get; set; }

    public string? user_agent { get; set; }

    public DateTime create_datetime { get; set; }

    public virtual agent_master? agent { get; set; }

    public virtual agent_delegation? delegation { get; set; }

    public virtual osolab_user? owner_osolab { get; set; }
}
