// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class agent_master
{
    public string agent_id { get; set; } = null!;

    public string owner_osolab_id { get; set; } = null!;

    public string agent_name { get; set; } = null!;

    public string secret_hash { get; set; } = null!;

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public DateTime? last_used_datetime { get; set; }

    public DateTime? revoked_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<agent_audit_log> agent_audit_logs { get; set; } = new List<agent_audit_log>();

    public virtual ICollection<agent_delegation> agent_delegations { get; set; } = new List<agent_delegation>();

    public virtual osolab_user owner_osolab { get; set; } = null!;
}
