// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class agent_delegation
{
    public string delegation_id { get; set; } = null!;

    public string agent_id { get; set; } = null!;

    public string owner_osolab_id { get; set; } = null!;

    public string client_id { get; set; } = null!;

    public string scopes { get; set; } = null!;

    public DateTime expires_datetime { get; set; }

    public DateTime? verified_datetime { get; set; }

    public DateTime? revoked_datetime { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual agent_master agent { get; set; } = null!;

    public virtual ICollection<agent_audit_log> agent_audit_logs { get; set; } = new List<agent_audit_log>();

    public virtual client_master client { get; set; } = null!;

    public virtual osolab_user owner_osolab { get; set; } = null!;
}
