// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class client_data_key
{
    public long sequence_id { get; set; }

    public string client_id { get; set; }

    public string data_key { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual client_master client { get; set; }

    public virtual data_key_master data_keyNavigation { get; set; }
}