// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class client_master
{
    public string client_id { get; set; } = null!;

    public string client_name { get; set; } = null!;

    public string client_secret { get; set; } = null!;

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<client_data_key> client_data_keys { get; set; } = new List<client_data_key>();

    public virtual ICollection<client_redirect_uri> client_redirect_uris { get; set; } = new List<client_redirect_uri>();

    public virtual ICollection<client_scope> client_scopes { get; set; } = new List<client_scope>();

    public virtual ICollection<client_term> client_terms { get; set; } = new List<client_term>();

    public virtual ICollection<user_client_scope_consent> user_client_scope_consents { get; set; } = new List<user_client_scope_consent>();

    public virtual ICollection<user_info> user_infos { get; set; } = new List<user_info>();

    public virtual ICollection<user_term_consent> user_term_consents { get; set; } = new List<user_term_consent>();
}