// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class client_redirect_uri
{
    public long sequence_id { get; set; }

    public string client_id { get; set; }

    public string redirect_uri { get; set; }

    public byte is_default { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual client_master client { get; set; }
}