// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class client_master
{
    public string client_id { get; set; }

    public string client_name { get; set; }

    public string client_secret { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<user_info> user_infos { get; set; } = new List<user_info>();
}