// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

/// <summary>
/// client_data_key class.
/// </summary>
public partial class client_data_key
{
    /// <summary>
    /// Gets or sets sequence_id.
    /// </summary>
    public long sequence_id { get; set; }

    /// <summary>
    /// Gets or sets client_id.
    /// </summary>
    public string client_id { get; set; }

    /// <summary>
    /// Gets or sets data_key.
    /// </summary>
    public string data_key { get; set; }

    /// <summary>
    /// Gets or sets create_datetime.
    /// </summary>
    public DateTime create_datetime { get; set; }

    /// <summary>
    /// Gets or sets update_datetime.
    /// </summary>
    public DateTime update_datetime { get; set; }

    /// <summary>
    /// Gets or sets status.
    /// </summary>
    public byte status { get; set; }
}
