// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class client_term
{
    public long sequence_id { get; set; }

    public string client_id { get; set; }

    public string term_id { get; set; }

    public string term_version { get; set; }

    public byte required { get; set; }

    public int display_order { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }
}