// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class data_key_master
{
    public string data_key { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public virtual ICollection<client_data_key> client_data_keys { get; set; } = new List<client_data_key>();
}