// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class jwk_master
{
    public long sequence_id { get; set; }

    public string kid { get; set; } = null!;

    public string kty { get; set; } = null!;

    public string alg { get; set; } = null!;

    public string key_use { get; set; } = null!;

    public string public_n { get; set; } = null!;

    public string public_e { get; set; } = null!;

    public byte[] private_key_ciphertext { get; set; } = null!;

    public byte[] private_key_iv { get; set; } = null!;

    public byte[] private_key_tag { get; set; } = null!;

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }
}