// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class osolab_user
{
    public string osolab_id { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public string nonce { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<user_info> user_infos { get; set; } = new List<user_info>();
}