// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class osolab_user
{
    public string osolab_id { get; set; } = null!;

    public string email { get; set; } = null!;

    public string password { get; set; } = null!;

    public string nonce { get; set; } = null!;

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<user_client_scope_consent> user_client_scope_consents { get; set; } = new List<user_client_scope_consent>();

    public virtual ICollection<user_info> user_infos { get; set; } = new List<user_info>();

    public virtual ICollection<user_term_consent> user_term_consents { get; set; } = new List<user_term_consent>();
}