// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class scope_master
{
    public string scope { get; set; } = null!;

    public string description { get; set; } = null!;

    public byte confidential_only { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<client_scope> client_scopes { get; set; } = new List<client_scope>();

    public virtual ICollection<scope_data_key> scope_data_keys { get; set; } = new List<scope_data_key>();

    public virtual ICollection<user_client_scope_consent> user_client_scope_consents { get; set; } = new List<user_client_scope_consent>();
}