// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class scope_data_key
{
    public long sequence_id { get; set; }

    public string scope { get; set; } = null!;

    public string data_key { get; set; } = null!;

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual data_key_master data_keyNavigation { get; set; } = null!;

    public virtual scope_master scopeNavigation { get; set; } = null!;
}