// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class term_master
{
    public string term_id { get; set; }

    public string term_type { get; set; }

    public string title { get; set; }

    public string version { get; set; }

    public string content { get; set; }

    public DateTime effective_start_datetime { get; set; }

    public DateTime? effective_end_datetime { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual ICollection<user_term_consent> user_term_consents { get; set; } = new List<user_term_consent>();
}