// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class user_client_scope_consent
{
    public long sequence_id { get; set; }

    public string osolab_id { get; set; } = null!;

    public string client_id { get; set; } = null!;

    public string scope { get; set; } = null!;

    public DateTime consented_datetime { get; set; }

    public DateTime create_datetime { get; set; }

    public DateTime update_datetime { get; set; }

    public byte status { get; set; }

    public virtual client_master client { get; set; } = null!;

    public virtual osolab_user osolab { get; set; } = null!;

    public virtual scope_master scopeNavigation { get; set; } = null!;
}