// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthFoundation.Models;

public partial class user_term_consent
{
    public long sequence_id { get; set; }

    public string osolab_id { get; set; }

    public string client_id { get; set; }

    public string term_id { get; set; }

    public string term_version { get; set; }

    public byte consent_result { get; set; }

    public DateTime consented_datetime { get; set; }

    public DateTime create_datetime { get; set; }

    public virtual client_master client { get; set; }

    public virtual osolab_user osolab { get; set; }

    public virtual term_master term { get; set; }
}